### ISSUE TITLE
Add all services supported by similar chat apps

### ISSUE THREAD

**Issue by jdegger** [philhudson91/SwagChat#7]

**Comment by phil-hudson** [comment]
we chat: https://web.wechat.com/

**Comment by justinholmes** [comment]
Campfire: https://launchpad.37signals.com/campfire/signin

**Comment by justinholmes** [comment]
freenode irc https://webchat.freenode.net/

**Comment by justinholmes** [comment]
oftc irc webchat.oftc.net

**Comment by phil-hudson** [comment]
<webview id="whatsapp" src="https://web.whatsapp.com" style="display: none;" nodeintegration></webview>
        <webview id="facebook-messenger" src="https://www.messenger.com" style="display: none;" nodeintegration></webview>
        <webview id="slack" src="https://slack.com/signin" style="display: none;" nodeintegration></webview>
        <webview id="skype" src="https://login.skype.com/login" style="display: none;" nodeintegration></webview>
        <webview id="we-chat" src="https://web.wechat.com/" style="display: none;" nodeintegration></webview>

**Comment by phil-hudson** [comment]
https://web.whatsapp.com
https://www.messenger.com
https://slack.com/signin
https://login.skype.com/login
https://web.wechat.com/

**Comment by phil-hudson** [comment]
do we need to add a reference to each service's font awesome icon?

**Comment by justinholmes** [comment]
go for it
